version: 0.2

phases:
  install:
    commands:
      - scripts/install.sh
  pre_build:
    commands:
    # Source the output of this script as it sets variables for later stage use
      - . scripts/pre_build.sh
  build:
    commands:
      - scripts/build.sh
  post_build:
    commands:
      - scripts/post_build.sh
