version: 0.2

phases:
  install:
    commands:
      - scripts/install.sh
  pre_build:
    commands:
      - scripts/pre_build.sh
  build:
    commands:
      - scripts/build.sh
  post_build:
    commands:
      - scripts/post_build.sh
